version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: >
      bash -c "python app.py"
    restart: always

